version: '2'
services:
    application:
        build: ./application
        container_name: project_application
        volumes:
            - /Users/robingodart1/www:/var/www
        tty: true
    manager:
        build: ./manager
        container_name: manager
        volumes_from:
            - application
        ports:
            - 8081:8081
    db:
        image: mysql
        container_name: mysql
        env_file:
            - ./env/mysql.env
        volumes:
            - /Users/robingodart1/docker/mysql/data:/var/lib/mysql:rw
        ports:
            - 3306:3306
    php:
        build: ./php7
        container_name: php
        volumes_from:
            - application
        ports:
            - 9000:9000
            - 9001:9001
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - 80:80
        volumes_from:
            - application
        volumes:
            - /Users/robingodart1/docker/logs/nginx:/var/log/nginx
        depends_on:
            - php
